color0 #181117
color1 #ffb4ab
color2 #ffa9fa
color3 #e9b7e3
color4 #ffb2bb
color5 #ffa9fa
color6 #e9b7e3
color7 #eddfe7
color8 #9d8c99
color9 #ffb4ab
color10 #ffa9fa
color11 #e9b7e3
color12 #ffb2bb
color13 #ffa9fa
color14 #e9b7e3
color15 #eddfe7

cursor                #eddfe7
cursor_text_color     #181117
background            #181117
foreground            #eddfe7
selection_foreground  #d4c1cf
selection_background  #50434e
active_border_color   #ffa9fa
inactive_border_color #50434e
url_color             #ffa9fa

active_tab_foreground   #5a005f
active_tab_background   #ffa9fa
inactive_tab_foreground #d4c1cf
inactive_tab_background #50434e
cursor_trail_color      #d4c1cf
